### ISSUE TITLE
How to upgrade elasticsearch-analysis-standardnumber to elasticsearch 2.2.2?

### ISSUE THREAD

**Issue by ghost** [jprante/elasticsearch-analysis-standardnumber#1]
@jprante , Could you please guide me how to upgrade that to elasticsearch 2.2.2. Thanks.

**Comment by jprante** [comment]
Thanks. I have just pushed out version 2.2.2.0 for Elasticsearch 2.2.2 and 2.3.3.0 for Elasticsearch 2.3.3

**Comment by ghost** [comment]
I got it, thanks jprante.
